name: Package Deployment

on:
    workflow_dispatch:

jobs:
    maven-deploy-prod:
        timeout-minutes: 5
        environment: repsy-prod
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker build
              run: cd maven; docker build -t repsy-hello-world-maven .

            - name: Run maven deployment container
              run: |
                docker run --rm \
                  -e REPSY_BASE_URL=${{ vars.REPSY_BASE_URL }} \
                  -e REPSY_USERNAME=${{ vars.REPSY_USERNAME }} \
                  -e REPSY_REPO_NAME=${{ vars.REPSY_REPO_NAME }} \
                  -e REPSY_REPO_PASSWORD=${{ secrets.REPSY_REPO_PASSWORD }} \
                  repsy-hello-world-maven
